# This is a basic workflow to help you get started with Actions

name: Test on node 18

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build library
        run: npm run build-2022

      - name: Run node unit tests
        run: |
          $env:NODE_ENV="production"
          npm start

      # - name: Upload Release
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Release
      #     path: build/Release
  build-windows-2019:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build library
        run: npm run build-2019

      - name: Run node unit tests
        run: |
          $env:NODE_ENV="production"
          npm start

      # - name: Upload Release
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Release
      #     path: build/Release
